name: Dec0mpose
version: ${project.version}
main: com.github.bryanser.dec0mpose.Dec0mpose
depend: [ BrAPI ]
authors: [ Bryan33 ]

commands:
    Dec0mpose:
        aliases: [fj,decompose]
        usage: |
            §6/<command> >> 打开分解界面
            §c/<command> open [player] >> 为玩家打开UI
            §c/<command> reload >> 重载插件
            §c/<command> add [消耗] [前置条件] >> 添加手上物品到分解结果中
            §c§l  范例/<command> add 10.5 1,2,3,4,5