Items:
    item1:
        name: '&7一级精炼石'
        value: 15
        level: 10
ItemLevel: '物品等级:'
SlotPosition:
    slot1:
        text:
            original: '&b○ &7<可精炼: 攻击力: +?>'
            result: '&b◉ &7<已精炼: 攻击力: +%var%>'
        expression: 'value * 0.5 + 1 + level + itemLevel'
        #显示的数字表达式
        # #.##表示保留两位小数, #.##%会自动计算成百分比(1为100.00%)
        format: "#.##"

UI:
    info:
        id: 111
        name: '&6精炼'
        lore:
            - '&6箱子信息'
    disable:
        id: 50
        durability: 4
        name: '&a红色玻璃'
        lore: []
    decoration:
        id: 54
        durability: 0
        name: '&a白色玻璃'
        lore: []
    able:
        id: 54
        durability: 1
        lore:
            - '&a可精炼: %original%'
    installed:
        id: 54
        durability: 3
        name: "&a已精炼"
        lore:
            - '&a已精炼: %result%'
            - '&eshift+右键点击卸除精炼'
    other:
        id: 1
        name: "&a睡莲位置"
        lore: []